spring.application.name=tienda-api

# H2 en modo DISCO (persistente entre ejecuciones)
spring.datasource.url=jdbc:h2:file:./data/tienda;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate crea/actualiza el esquema de forma automática
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Consola H2 web (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

server.port=8080